spring.application.name=myhouseexpenses
spring.datasource.url=jdbc:postgresql://localhost:5432/fintrack
spring.datasource.username=fintrack
spring.datasource.password=fintrack
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# Chatgpt disse que ajudava
spring.jpa.open-in-view=false